quote=[
 {img:"https://drive.google.com/uc?id=14wYswXtM4rwSzlBa1IAzaaqOhiyIgY5U"},
 {img:"https://drive.google.com/uc?id=14t_XXPhfQuv70xh6ggX1avvK7m7N6ALQ"},
 {img:"https://drive.google.com/uc?id=1509mGI7yG0ycf1iW7WdTFrcFsg-BNbIl"},
 {img:"https://drive.google.com/uc?id=14tTIMRUHky3lfgyDisNGQWPbOIwMi_BF"},
 {img:"https://drive.google.com/uc?id=14mDrQPrreOfMAsEcz5htiLvN8GyhY0Cw"},
 {img:"https://drive.google.com/uc?id=14sCwJ27wLNOZK_MBcSotYKZslEkVXm_4"}
 ];
 module.exports=quote;
